version: "3.8"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.2.0
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: sqlite:////mlflow/mlflow.db
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /mlflow/mlruns
      GIT_PYTHON_REFRESH: quiet
    volumes:
      - ./mlflow:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000

  app:
    image: varunseth2303/iris-mlops:latest
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mlflow
    volumes:
      - ./mlflow:/mlflow
      - ./src:/app/src

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
