name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start MLflow server
        run: |
          nohup mlflow server \
            --host 127.0.0.1 \
            --port 5000 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root ./mlruns \
            > mlflow.log 2>&1 &
          sleep 5  # give it time to start

      - name: Run pytest
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: |
          pytest
